version: 2
updates:
    - package-ecosystem: 'maven'
      directory: '/'
      schedule:
          interval: 'daily'
          time: '04:00'
      open-pull-requests-limit: 3
      pull-request-branch-name:
        separator: "-"
      commit-message:
        prefix: "Dependency Update: "

    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
          time: '04:00'
      open-pull-requests-limit: 3
      pull-request-branch-name:
          separator: "-"
      commit-message:
          prefix: "GitHub Action Update: "
