= Semantic Versioning Parser

image:https://javadoc.io/badge2/io.github.freiheitstools.semver.parser/parser/javadoc.svg[]
image:https://img.shields.io/maven-central/v/io.github.freiheitstools.semver.parser/parser[link="https://central.sonatype.com/search?namespace=io.github.freiheitstools.semver.parser"]
image:https://github.com/freiheitstools/semver-lib/actions/workflows/build-and-test.yaml/badge.svg?branch=baseline/0.1/development["GitHub Actions Status", link="https://github.com/freiheitstools/semver-lib/actions/workflows/build-and-test.yaml"]

'''

The _Semantic Versioning Parser_ is a Java library for parsing and building semantic versions according to the https://semver.org/[Semantic Version Specification].
It requires Java 17 or higher.

== Maven Dependency

.Maven Dependency Declartion for the library
[source,xml]
----
<dependency>
    <groupId>io.github.freiheitstools.semver.parser</groupId>
    <artifactId>parser</artifactId>
    <version>0.1.0</version>
</dependency>
----

Please check afterward for the latest version by running the following Maven command:

.Use Maven to check for the latest Maven version
[source]
----
mvn versions:display-dependency-updates \
  -DdependencyIncludes="io.github.freiheitstools.semver.parser:parser"
----

== Usage Examples

.Parsing a given Semantic Version
[source,java]
----
 SemVerParser parser = SemVer.parser();

 SemVer semver = parser.parse("1.2.3-SNAPSHOT+23");

 if (semver.isInvalid()) {
    System.out.println("Given semantic version is not valid");
 } else {
    System.out.println(semver.getMajor());
    System.out.println(semver.getMinor());
    System.out.println(semver.getPatch());

    semver.getPreRelease().ifPresent(System.out::println);
    semver.getBuild().ifPresent(System.out::println);
 }
----

.Building a new Semantic Version from an existing one
[source,java]
----
SemVerParser parser = SemVer.parser();
SemVer semVer = parser.parse("1.2.3-SNAPSHOT");

SemVer nextSemVer = SemVer.builder().startFrom(semVer)
                          .removePrerelease()
                          .build();

----

.Building a new Semantic Version from scratch
[source,java]
----
SemVer nextSemVer = SemVer.builder().startFrom(1, 2, 0)
                          .setPrerelease("SNAPSHOT")
                          .build();
----

== Versioning of the Library

The versioning of the Semantic Versioning Parser takes place according to the principles of https://semver.org[Semantic Versioning^].
This means that the version of a release is only a statement on compatibility, not of functionality.

As every good open source project, it is never complete.

== Building the Library

The projects used Apache Maven to build.
So a simple call to Maven without any goal will build the library.

.Building the project via Apache Maven
[source,shell]
----
mvn
----

=== Disabling any style checks during the build

The project uses the https://github.com/diffplug/spotless/[Spotless] to ensure a consistent layout and style for various artefacts.
You can disable this check during development time by disabling the profile used to run Spotless by running Maven with `-P!run-spotless-to-check-project`.

.Building the Library without the checks by Spotless
[source,shell]
----
mvn -P!run-spotless-to-check-project
----

You can also add this option to your `.mvn/maven.config` file to persist this setting.

.Disabling the profile via `.mvn/maven.config`
[source,shell]
----
echo "-P!run-spotless-to-check-project" >> .mvn/maven.config
----

==== Using Spotless to ensure a consistent layout

To achive the required layout for various artefacts, you can call the `apply` goal of Spotless.
Make sure that Spotless has not been disabled.

.Formatting the project with Spotless
[source,shell]
----
mvn spotless:apply
----
