name: Build and Test

on:
    workflow_dispatch:
    push:
    schedule:
        # Build regularly on the first day of each month the project
        - cron: 0 2 1 * *

jobs:
    build-and-test:
        name: 'Build and Test'
        strategy:
            matrix:
                version: [22, 23]

        runs-on: ubuntu-latest

        steps:
            - name: Checkout Git Repository
              id: git-checkout
              uses: actions/checkout@v4

            - uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '${{ matrix.version }}'

            - name: Show Versions of used tools
              run: |
                echo "GRAALVM_HOME: $GRAALVM_HOME"
                echo "JAVA_HOME: $JAVA_HOME"
                echo "Version of JDK:" $(java --version)
                echo "Version of Apache Maven:" $(mvn --version)

            - name: Setup local cached Maven Repository
              id: setup-cached-repo
              uses: actions/cache@v4
              env:
                  cache-name: maven-local-repository-cache
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-build-${{ github.run_id }}

            - name: Build
              id: maven-build
              run: |
                  mvn --no-transfer-progress --batch-mode clean verify
